baseURL = 'https://thejewelry.business/'
defaultContentLanguage = 'uk'
defaultContentLanguageInSubdir = true
title = 'The Jewelry Business'
theme = 'serif' # Змінюємо на Serif

[languages]
  [languages.uk]
    languageName = 'UA'
    contentDir = 'content/uk'
    weight = 1
    title = 'Ювелірний Бізнес: Аналітичний Центр'
  [languages.en]
    languageName = 'EN'
    contentDir = 'content/en'
    weight = 2
    title = 'The Jewelry Business: Digital Hub'
  [languages.pt]
    languageName = 'PT'
    contentDir = 'content/pt'
    weight = 3

[params]
  author = 'Anna Pivtorak'
  description = 'Analytical Center & Heritage Archive of Jewelry Art'
  logo = 'the-jewelry-business-00-logo-2026.webp' # Важливо підготувати лого або залишити текст
  
  # Налаштування для теми Serif
  footer_copyright = '© 2002-2026 The Jewelry Business. Under the leadership of Anna Pivtorak.'
  contact_email = 'editor@thejewelry.business'

# Головне меню, яке відображає наші нові стратегічні напрямки
[[menu.main]]
    name = "Jewelry Manufacturing"
    url = "/jewelry-manufacturing/"
    weight = 1

[[menu.main]]
    name = "Luxury & Style"
    url = "/luxury-and-style/"
    weight = 2

[[menu.main]]
    name = "Intelligence & Heritage"
    url = "/intelligence-and-heritage/"
    weight = 3
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true # Дозволяє вставляти калькулятори через HTML-коди
